apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: game-server
  labels:
    app: game-server
spec:
  serviceName: "game-server"  # Must match the headless service name
  replicas: 3  # Number of game server instances
  selector:
    matchLabels:
      app: game-server
  template:
    metadata:
      labels:
        app: game-server
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: game-server
        image: ghcr.io/iercann/test-game-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: websocket
          containerPort: 8080
          protocol: TCP
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: TICK_RATE
          value: "20"
        # Each pod knows its own identity for state management
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GAME_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5