apiVersion: v1
kind: Service
metadata:
  name: game-server-external
spec:
  type: NodePort
  selector:
    app: game-server
  ports:
  - port: 8080
    targetPort: 8080
    # nodePort will be assigned automatically in the range 30000-32767