apiVersion: v1
kind: Service
metadata:
  name: game-server  # Must match the StatefulSet's serviceName
  labels:
    app: game-server
spec:
  clusterIP: None  # This makes it a headless service
  ports:
  - port: 8080
    targetPort: 8080
    name: websocket
  selector:
    app: game-server